package com.coders.tourism.Favorite;

import android.content.Context;
import android.content.SharedPreferences;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;
import androidx.annotation.Nullable;
import androidx.fragment.app.Fragment;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;
import com.coders.tourism.R;
import com.coders.tourism.Recommened.Fragments.Items;
import java.util.ArrayList;
import java.util.Map;

public class RecycleFavorite extends Fragment {
    ArrayList<Items> arr;
    Context c;
    @Override
    public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        View v = inflater.inflate(R.layout.fragment_favorite, container, false);
        TextView found=v.findViewById(R.id.found);
        c=getActivity().getApplicationContext();
        arr = getData();
        SharedPreferences prefs = c.getSharedPreferences("FAVORITE", c.MODE_PRIVATE);
        Map<String, ?> allEntries = prefs.getAll();
        ArrayList<Items> send=new ArrayList<>();
        for (Map.Entry<String, ?> entry : allEntries.entrySet()) {
            for(int i=0;i<arr.size();i++){
                if(entry.getKey().equals(arr.get(i).name)){
                    send.add(arr.get(i));
                }
            }
        }
        if(send.size()==0)
            found.setVisibility(View.VISIBLE);
        else
            found.setVisibility(View.INVISIBLE);
        RecyclerView recyclerView = v.findViewById(R.id.favorite_recycler);
        recyclerView.setLayoutManager(new LinearLayoutManager(c));
        recyclerView.setAdapter(new RecyclerAdapter(found,send, c));
        return v;
    }
    private ArrayList<Items> getData() {
        ArrayList<Items> arr = new ArrayList<>();
        arr.add(new Items("Cairo Tower", R.drawable.cairotower, "02 27365112", 30.045910, 31.224289, "The Cairo Tower is a landmark in Cairo, where many tourists want to visit, in order to enjoy the distinctive design, which symbolizes the ancient Egyptian civilization, it consists of sixteen floors, and a base of Aswan granite stones, used by the ancient Egyptians, to build At present, the number of visitors to this tower, especially visitors from Arab countries, who wish to climb to its roof, which is characterized by its magnificent view of Cairo, where the duration of the climb to the surface does not take more than seconds, through which Tourists can see many important places in Egypt such as TV building, Sphinx, Nile, Salah El-Din castle, Al-Azhar and Pyramids, in addition to the visitors' ability to have lunch in the restaurants available in this tower, the most important of which is the circular restaurant located on the 14th floor, which Rotating around a focal point that enables the visitor to see Cairo, and contains nineteen tables, each accommodates five people, and the possibility of enjoying different types of juices and drinks from the top of the tower"));
        arr.add(new Items("Mosque of Muhammad Ali", R.drawable.mohamedali, "null", 30.028699, 31.259916, "The mosque consists of a rectangular form divided into two parts: the eastern section, which is the house of prayer or the campus of the mosque, and the western section, which is the courtyard with a watering hole. Each section has two opposite doors, that is, the mosque has four doors, and from the door in the middle of the sea wall of the mosque we enter the courtyard, which is a large courtyard area of \u200B\u200Babout 53 × 54 meters under a cistern, surrounded by four galleries with marble columns carrying columns Small domes carved on the inside and overlaid on the outside with lead plates with copper crescents.\n" +
                "In the center of the open courtyard we find a dome of ablution established in 1263 AH - 1844 AD with a wooden flap and built on eight marble pillars and the interior of this dome decorated with colorful paintings representing landscapes influenced by Western style. Inside this dome is another eight-sided dome with a marble crescent inscribed with prominent motifs, grape clusters, and a colorful pattern inscribed with Persian calligraphy by the calligrapher \"Sinklach\" Koranic verses of ablution, and bearing the date in 1263 (1863 AH)."));
        arr.add(new Items("Srabyom", R.drawable.srabyom, "null", 30.516825, 32.331061, "Sarabium is an archaeological temple located in the hill pillar area. This temple was of tourist importance as a place of healing, flocked to patients or seekers healing through dreams or so-called incubation of the disease, where there were rooms around a temple for the accommodation of these patients worshiped to the goddess Serapis"));
        arr.add(new Items("Pompey's Pillar", R.drawable.pompeyspillar, "null", 31.182330, 29.896299, "Column Sawari is a Roman archaeological column located in the city of Alexandria in Egypt, and is one of the most famous monuments in it. It was built on Tell Bab Sidra between the area of the current Muslim cemetery known as Al-Amoud cemetery and the archaeological plateau of Kom el Shoqafa. It is about 27 meters long and is made of red granite."));
        arr.add(new Items("Lighthouse of Alexandria", R.drawable.lighthouseofalexandria, "null", 31.214238, 29.891324, "The lighthouse of Alexandria or the lighthouse of Alexandria - Pharos Alexandria - one of the seven wonders of the world mentioned by the Greeks, and its location on the edge of the Pharos Peninsula, the current place of Qaitbay Castle in Alexandria, Egypt. Considered the first lighthouse in the world. It was built by Sostratus during the reign of Ptolemy II in 270 BC It was 120 meters high and was destroyed in an earthquake in 1323."));
        arr.add(new Items("Cairo Citadel", R.drawable.cairocitadel, "02 25121735", 30.029884, 31.261081, "The Citadel of Salah al-Din or the Citadel of the Mountain is a castle located on Mount Mokattam"));
        arr.add(new Items("Citadel of Qaitbay", R.drawable.citadelofqaitbay, "null", 31.214006, 29.885649, "This castle is located at the end of the island of Pharos in the far west of Alexandria. From its construction in 884 AH."));
        arr.add(new Items("Mosque-Madrassa of Sultan Hassan", R.drawable.madrassaofsultanhassan, "null", 30.032278, 31.256175, "Mosque, school and dome of Sultan Nasser Hassan or Sultan Hassan's school or Sultan Hassan Mosque is one of the famous archaeological mosques in Cairo. Described as the Dora of Islamic Architecture in the East, it is the most harmonious and harmonious monument of Islamic Cairo, and represents the maturity of Mamluk architecture."));
        arr.add(new Items("Bibliotheca Alexandrina", R.drawable.bibliothecaalexandrina, "03 4839999", 31.208869, 29.909201, "The ancient Bibliotheca Alexandrina, known as the Royal Library of Alexandria, or the Great Library, is the largest library of its time. The library was subjected to numerous fires"));
        arr.add(new Items("Ras Am Side",R.drawable.rasamside,"069 3661815",27.858079, 34.316497,"Divers go to be impressed by the stunning coral forms, especially coral reefs, as well as the abundance of aquatic life, including various rare fish species, the area is located 5 km from Naama Bay."));
        arr.add(new Items("Sharm El Loly",R.drawable.loly,"0111 372 3483",24.556537, 35.150605,"One of the most beautiful beaches in the world, which has recently become renowned, and has achieved advanced positions in the rankings of global beaches, as the traveler will feel that he is in one of the beaches (Maldives) charming."));
        arr.add(new Items("Zeytuna Beach",R.drawable.zeytuna,"065 3580350",27.401446, 33.681399,"It is the most important beaches of the city of El Gouna, and the village of El Gouna is one of the most important and most beautiful suburbs of Hurghada."));
        arr.add(new Items("agiba beach",R.drawable.agiba,"0110 115 3532",31.414413, 27.006642,"One of the most beautiful beaches of all time, and is characterized by the wonderful rock forms that dot it, which gave him this name."));
        arr.add(new Items("Ras Shitan",R.drawable.rasshitan,"0100 101 3772",29.135239, 34.687375,"In the north of Nuweiba near Dahab, an area characterized by its tranquility and charming nature, you can stay in a tent on the beach and enjoy diving and swimming."));
        arr.add(new Items("Mahmya",R.drawable.mahmya,"0100 111 9792",27.182654, 33.958374,"Called the Paradise of God on Earth, it is your favorite destination for snorkeling and breathtaking views. Giftun Island is located near Hurghada and features a white sand beach and clear water."));
        arr.add(new Items("Mahmya Abu Galum",R.drawable.abugalum,"null",28.732113, 34.625495,"Famous for its colorful coral reefs, it is also an area of safari and camel rides."));
        arr.add(new Items("Taba",R.drawable.taba,"null",29.491665, 34.896903,"Located between Taba and Nuweiba, with clear blue waters and picturesque coral reefs, the Strait is the perfect place for professional divers."));
        arr.add(new Items("El Arish",R.drawable.elarish,"null",31.132404, 33.802807,"The beach is known as «Palm», due to the presence of palm tree forests along its length, and is characterized by the presence of the Corniche, which provides all tourist services."));
        arr.add(new Items("Nile Cruise",R.drawable.nilecruise,"0109 731 0207",30.023669, 31.218219,"One of the best places to stay in Cairo at night in front of the magnificent view of the Nile is the independence of one of the floating vessels fixed or moving, on which the various artistic items such as concerts, singing, belly dancing and folklore, in addition to delicious meals and tastier drinks.\n" + "One of the most famous is Neil Maxim in front of the Marriott Hotel in Zamalek, the Grand Hyatt of the hotel of the same name in Garden City, Al Saraya and Nile City in Zamalek or Al Jazeera near the October Bridge, among others.\n" + "If you want a Nile cruise away from the hustle and bustle you can take a simple traditional boat from the Corniche area in Zamalek or Maadi, where you enjoy the atmosphere of tranquility and recreation alone in the presence of the great Nile. If you like to socialize with the local population in its simplest form, here are the Nile Cruises with the River Bus, which is a means of entertainment at the same time. Do not miss the best aspects of tourism in Cairo and enjoy a wonderful Nile cruise by any means of hiking and transport to your liking"));
        arr.add(new Items("Aqua Park",R.drawable.aquapark,"02 24772246",30.172981, 31.538445,"The water parks are one of the most important places of entertainment in Cairo and an ideal destination for children and families and for all those seeking fun and enjoyment and adventure. Cairo is home to three of Egypt's oldest and largest water parks: Aqua Park on the Cairo-Ismailia Desert Road, Crazy Water in Sheikh Zayed and Fun Zoom inside the walls of the Sun Club in Nasr City. The industrial area, with a play area suitable for young children, makes it one of the most important places to go out in Cairo for families."));
        arr.add(new Items("Maadi Island",R.drawable.maadiisland,"null",29.965525, 31.239242,"Located on the Nile Corniche, specifically in the Maadi area of \u200B\u200Bthe most beautiful tourist sites in Cairo. The island has a wide range of exhilarating greenery, walking around, hiking, golfing or horse-drawn carts. In addition to water streams and artificial lakes that are crossed over wooden bridges that provide the visitor with unspeakable pleasure, these lakes also provide an opportunity to ride the boat and enjoy an interesting Nile cruise for a small fee. Restaurants, cafes and shaded areas operate on a minimum order basis but are reasonably priced, but the island does not allow foreign visitors to enter only Egyptians and Arabs."));
        arr.add(new Items("Key Action Sports Al Rehab",R.drawable.keyactionsportsalrehab,"0111 307 2722",30.065090, 31.489051,"One of the most suitable places of entertainment in Cairo for fans of adventure and fun and play, where the place depends on the idea of simulating wars, but between groups of friends in several scenarios and using fake bullets and uniforms of the place. One of the best places to go out in Cairo for young people is located in Al Rehab City Club on the Cairo-Suez Desert Road not far from Cairo International Airport."));
        arr.add(new Items("KidZania",R.drawable.kidzania,"null",30.031233, 31.405695,"It is like a fully integrated, closed community designed for children, located inside Cairo Festival City Mall in New Cairo, one of Cairo's most entertaining and fun places for children. In KidZania, your child is treated as a mature adult who works in the profession that he wishes to work in. Going out in Cairo for families with children aged 4-14 years."));
        arr.add(new Items("Egyptian Museum",R.drawable.egyptianmuseum,"02 25794596",30.047014, 31.233649,"One of the most important tourist attractions in Cairo and Egypt in general; it is one of the largest museums area and collections, as the ancient museum contains about 150 thousand pieces dealing with the history of Egypt Pharaonic, Roman and Greek divided on two floors; one contains light collections such as small statues, manuscripts and pictures, and the other includes heavy pieces such as coffins and mummies However, you may need to have a private tour guide with you or your tour group to explain the evolution of Egyptian historical eras in their historical order, or you can use the guides and posters placed by the museum's management. Side of the exhibits. From the outside, the museum has a magnificent red-clad architectural design as well as its distinctive dome and windows that make it very similar to Islamic architecture."));
        arr.add(new Items("Coptic Museum",R.drawable.copticmuseum,"02 23628766", 30.005558, 31.230136,"Located next to the famous Roman fortress of Babylon, the Coptic Museum is the largest museum of Egyptian Coptic antiquities in the world, where you will see the most important collections dating back to the Coptic era of Egyptian history, which number about 16,000 artifacts from different regions of Egypt. The museum is characterized by its stone structure with a distinctive architectural design that mimics its era, and its beautiful facade resembling the mosque of the moon, and in front of it a statue of the founder of the museum, \"thick discotheque Pasha\" decorates its entrance, which was opened in 1910."));
        arr.add(new Items("Museum of Islamic Art",R.drawable.museumofislamicart,"02 23901520",30.044402, 31.252358,"The Museum of Islamic Art is located in Bab El-Khalq, one of the most important tourist attractions in Cairo and one of the largest Islamic museums in the world that simulates the era of Islamic rule in Egypt. For the Islamic era of glass and metal utensils, furniture, valuable stones, letter writing equipment, manuscripts, with information to give you what you see in Arabic and English and provides a corner for children."));
        arr.add(new Items("6th of October Panorama",R.drawable.thofoctoberpanorama,"02 24022317",30.074269, 31.306808,"The October War Panorama is one of Cairo's most important landmarks for history lovers. The performances are on display at the museum's theater, whose building appears from the outside in the form of a majestic circular building occupying a large area on Salah Salem Road.\n" +
                "Official working hours of the October War Panorama: Daily except Tuesday: 1- Morning 3 concerts 9.30, 11.00 and 12.30. 2- Evening: Two summer concerts: 6.00 and 7.30. Winter: 5.00, 6.30\n" +
                "October War Panorama Address: Salah Salem Street, Beside Cairo Stadium, Nasr City, Cairo ?, Egypt"));
        arr.add(new Items("Abdeen Palace",R.drawable.abdeenpalace,"02 23916909",30.042999, 31.247783,"One of the most important tourist places in Cairo reviews the history of the modern monarchy starting from the era of Khedive Ismail, who made a decision to build the palace in the last quarter of the 19th century until the end of the monarchy in Egypt by the 1952 revolution.\n" +
                "Located in the center of Cairo, the palace showcases this era of Egyptian history through a collection of museums in its surroundings, displaying the precious belongings of the royal family and the weapons used during their reign, as well as dedicated gifts from world presidents. An explanation is given by a guide appointed by the place management for a small fee.\n" +
                "During the journey between the various museums of the Abdin Palace, you can admire the beauty of the gardens and the vast green spaces that cover the surroundings of the palace and its outer roads, designed to emulate the history of its era."));
        arr.add(new Items("Alexandria Aquarium",R.drawable.alexandriaaquarium,"null",31.212797, 29.885005,"The Aquarium in Alexandria is a small museum that includes several species of fish and animals of the Mediterranean and Red Bahrain, as well as other species living in fresh water such as the Nile and the Amazon. Established in 1930, the museum is located near the Qaitbay Citadel in Anfoushi. In addition to the museum, the site includes an aquatic research institute."));
        arr.add(new Items("Alexandria National Museum",R.drawable.alexandrianationalmuseum,"03 4835519",31.200684, 29.913234,"Alexandria National Museum is one of Alexandria's museums in Egypt. The museum contains more than 1,800 artifacts representing most of the ages that passed to the city, which was founded in 332 BC. Address 110 Freedom Road."));
        arr.add(new Items("Graeco-Roman Museum",R.drawable.graecoromanmuseum,"050 2080119",31.199149, 29.906600,"The Greco-Roman Museum is a museum of archeology in Alexandria, Egypt. It presents a wide variety of antiquities found in Alexandria and its surroundings, most of which are from the Ptolemaic and subsequent Roman eras, especially since the emergence of Alexandria from the 3rd century BC to the 3rd century AD."));
        arr.add(new Items("Royal Jewelry Museum",R.drawable.royaljewelrymuseum,"03 5828348",31.240696, 29.963302,"The Royal Jewelry Museum is a museum displaying the jewelry of the royal families that ruled Egypt, and is located in Alexandria."));
        arr.add(new Items("Al-Azhar Park",R.drawable.alazharpark,"0114 440 0555",30.040759, 31.264740,"You will not need a special day to visit this beautiful park; it is not far from many of the tourist attractions in Cairo included in this article such as the Citadel of Salah al-Din and Sultan Hassan Mosque, one of the largest parks in Egypt and one of the most beautiful tourist attractions in Cairo and you will miss a lot if not You visit. The park offers you the opportunity to enjoy around 80 acres of greenery that surrounds you from every direction, a large fountain welcomes you on entry, water channels with small fountains distributed in different parts of the park, artificial waterfalls, roaming opportunities and wonderful sessions, restaurants and cafes, as well as sessions Morning and evening photography and weddings take place at events and weddings, making it one of Cairo's best nightlife venues and a good opportunity to socialize with the local customs."));
        arr.add(new Items("fustat park",R.drawable.fustatpark,"null",30.014781, 31.245250,"The Fustat park spans only 250 acres of greenery, making it a great spot for nature lovers and one of Cairo's oldest and largest parks. Near the park is the traditional crafts center and Fustat market, where you can enjoy seeing the most beautiful crafts and buying what you desire, while buying products and goods you will not find anywhere else, some made entirely of natural materials."));
        arr.add(new Items("The International Garden",R.drawable.theinternationalgarden,"02 23826579",30.049413, 31.336507,"Located in the Nasr City district, one of Cairo's most beautiful outings for families, it is an ideal destination for children, with a mini-zoo with a stuffed animal museum, along with a train that takes kids and adults on a short, fun tour around the spacious park and themed rest areas. Besides a wide variety of plants and flowers brought from all over the world, it is a joint venture between several countries whose flags will be installed at the entrance. Next to the international park is the beautiful theme park Wonderland, and you can go to Wonderland for fun games. Diverse and exciting then rest and recuperation in the international park, and next to them you will find a number of restaurants and cafes to eat fast food and drinks."));
        arr.add(new Items("Japanese Garden",R.drawable.japanesegarden,"0127 041 8322",29.848839, 31.340225,"One of Cairo's unique tourist attractions makes you feel as if Asia is in your hands while you are in North Africa. Built in the early 20th century in the Helwan district, the Japanese Garden is designed to represent East Asian civilizations. This is in addition to the natural scenery such as hills, trees and fish ponds, all this to the rhythms of live music emitted from the so-called garden stall making it a place to go out in Cairo suitable for families."));
        arr.add(new Items("Al-Andalus Garden",R.drawable.alandalusgarden,"null",30.044155, 31.227450,"One of the best tourist sites in Cairo for those looking for tranquility and recreation, where the park includes large areas of greenery and palm trees with vineyards overlooking the magnificent view of the Nile directly directly separated by only a wall of marble in a wonderful painting. In addition, you can take commemorative photos with the distinctive Andalusian arches, the black fountain and giant pharaonic statues next to the famous writer Ahmed Shawky, while enjoying the Andalusian architectural style that characterizes the garden located in Zamalek in front of the Teachers Club from the moment you enter it."));
        arr.add(new Items("Family Park",R.drawable.familypark,"0115 966 1880",30.042043, 31.225927,"The Freedom Park is one of Cairo's unique tourist attractions.It is not only based on green spaces, it was originally built to include statues of the greatest personalities who contributed to the freedom of their countries at the political and economic level or even through their writings and poems enthusiastic and influential. These statues represent Egypt in the figures of writers Ahmed Shawky and Hafez Ibrahim, the great economist Talaat Harb, as well as eight other statues of great figures who have influenced the history of freedom representing Mexico, Venezuela, and Ecuador. So, if you are looking for a cultural and historical meal, your visit to the park will be more fruitful."));
        arr.add(new Items("Maryland Park",R.drawable.marylandpark,"null",30.097928, 31.319005,"One of the most important places of entertainment in Cairo, and the largest gardens of the Heliopolis area. Spread over 50 acres of greenery and shady trees, this park features a beautiful lake where a small boat can be boarded, with skiing areas, as well as a range of upscale restaurants and cafés."));
        arr.add(new Items("DownTown",R.drawable.downtown,"02 23146182", 30.047736, 31.262256,"Downtown is one of the newest, largest and most beautiful shopping malls that you should not miss while visiting Cairo. Your family is one of the best places to go out in Cairo.\n" +
                "After this long tour of the most prominent tourist places in Cairo, we hope dear reader that you have decided where to go when you come to Egypt and during tourism in Cairo. Crazy Water Address: Plot A, 90th Street, 5th Settlement, New Cairo, Cairo ?, Egypt"));
        arr.add(new Items("Genena Mall",R.drawable.genena_mall,"02 20820621",30.061157, 31.332025,"One of the largest shopping malls you can visit while visiting Cairo, specifically in Nasr City. Next to its many shops and restaurants, the mall has its own ice-skating lounge. Genena Mall Address: 9 El Batrawy St., Off Abbas El Akkad Street, Nasr City, Cairo ?, Egypt"));
        arr.add(new Items("Khan El Khalili",R.drawable.khanelkhalili,"null",30.047736, 31.262256,"One of the most important tourist destinations in Cairo by Arab and foreign tourists and even local people; it is a popular market dating back to 6 centuries ago and is located near the neighborhood of Hussein. With Khan Al-Khalili you can buy the most beautiful souvenirs that remind you of your trip to Egypt from wood, copper and silver crafts, figurines, luminous glass lamps and more. While still enjoying the design of the place, the ancient Fatimid architecture has been preserved to date. Khan El Khalili Address: Aesthetic Department, Cairo ?, Egypt"));
        arr.add(new Items("City Stars Mall",R.drawable.citystars,"02 24800500",30.072978, 31.346046,"For shopping and entertainment lovers, one of the most important places of tourism in Cairo “City Stars” in Nasr City, where you can buy goods from the most famous local and international brands through a large number of shops in the mall on the five floors, as well as eat delicious and delicious meals and drinks in the most luxurious restaurants and cafes scattered in Place. The center also includes cinemas and distinctive halls for adult and young games, the most famous of which is iZone, Magic Galaxy, which provides billiards, bowling and video games in exchange for special cards that are bought and shipped with money as a calling card or Visa. City Stars Address: City Stars, Nasr City, Cairo ?, Egypt"));
        arr.add(new Items("Snow City",R.drawable.snowcity,"02 22692258",30.073651, 31.347365,"Zorb Ball is a giant ball that is inside it and descends on a cliff that really works and you can live and play videos. Ice Bumper Car, collision cars but in the snow. Skating, skiing with skiing tools as if you were in Russia already .. And the school inside the place you can learn to ski on the hands of foreign experts. The most important thing you can enjoy in the city of snow, is a winding slope where you sit on a sled on the ground, and take the winding ramp in a truly exciting atmosphere. Play Zone - Playing Zone, an open space full of snow, you can enjoy real games of ice balls or making shapes and snow houses .. Children can do many activities. Wooden House, a wooden place where you and your friends can imagine a high place panorama you can imagine with every place you play. The activities of Snow City are not just play-based. Educational activities are also available to families, schools and community groups, such as building an ice lolly hut and learning how to ski on a beginner's slope."));
        arr.add(new Items("Sharm El Sheikh",R.drawable.sharmelsheikh,"null",27.91582,34.32995,"When you meet the sea and the desert in one spot, you are certainly on a date with a charming adventure and breathtaking beauty, and this is what Sharm el-Sheikh hotels offer to its lovers, where the sea and the turquoise beaches that embrace the warm sun to create an oasis of comfort and relaxation from the trouble of bustling life. One of the most beautiful natural areas suitable for diving and exploring the coral reefs and creative marine life, and a short visit from Sharm El-Sheikh Beach to the island of \"Tiran\" located in the reserve will prove this talk, you can dive with the world of fish and strange creatures buried in the belly of the sea, while \"Shark Bay\" does not contain medicine It includes a bunch of the most luxurious resorts and beach hotels with stunning views and fine restaurants, equip many bottles of water, glasses and sunscreen caps and embark on a journey of suspense to the mysterious oases and deserts of Sinai, and enjoy a night in the hospitality of the Bedouin with Arabic coffee and brilliant stars In the clear sky of the desert, you will have the strange feeling of safety and peace we lack these days."));
        arr.add(new Items("Hurghada",R.drawable.hurghada,"null",27.25738,33.81291,"It is a busy three-hour trip to Luxor, while half an hour away from El Gouna and an hour from Safaga.Hurghada offers a world of luxury resorts and hotels that compete in its services and features, in addition to many entertainment cities. Water for children and families such as Makadi Water World and Aqua Park Jungle. The Marina is one of the most popular tourist areas, with a yacht marina and a wide pier shaded by beautiful palm trees, with dozens of restaurants, cafes and shops. From the most beautiful Shaw The world's coasts, characterized by shallow turquoise waters and white sand spotless, Hurghada represents a practical option to enjoy the sea and launch trips to the rest of the famous Egyptian cities."));
        arr.add(new Items("Sahl Hasheesh",R.drawable.sahlhasheesh,"null",27.016393,33.882691,"Sahl Hasheesh is located half an hour south of Hurghada Airport, one of the newly created huge tourist projects, to serve as a luxury tourist village that fascinates tourists with its facilities, beaches and luxury resorts. Luxury yachts, top-class golf courses, a horseback riding club and various sports centers. The most important resorts in this region are Palm Beach Piazza and Aubrey Sahl Hasheesh. These hotels offer an unparalleled tourist experience for high-cost trips. G temperatures mild winter, while in summer heat rises dramatically."));
        arr.add(new Items("Gouna",R.drawable.gouna,"null",27.394339,33.658090,"Also close to Hurghada and 22 km north of Hurghada Airport is the upscale tourist area \"El Gouna\", which is a large sunny and mild resort throughout the year and offers comfort, relaxation and privacy for travelers looking for calm and away from the hustle and bustle. Especially for swimming, one of the areas that attract lovers of marine sports, where diving, sailing, windsurfing, sailing and water skiing with rope, El Gouna consists of several neighborhoods designed intimate and tasteful, and has a large hospital and golf courses and spa centers Zaytuna Beach is the most beautiful beach in addition to the marina yacht \"Marina Abu Tig\", which extends on the coast a wonderful selection of restaurants and cafes with balconies overlooking the sea, and small boutiques selling gifts and souvenirs"));
        arr.add(new Items("Safaga",R.drawable.safaga,"null",26.750392,33.936661,"Safaga is about 53 km south of Hurghada, a quiet tourist area that does not experience much congestion, such as in Hurghada and Sharm El Sheikh, Safaga includes a group of cottages and small tourist villages with a sandy beach shallow and clear and beneficial to health, characterized by sunny weather and mild weather for days Surfing and snorkeling are among the most important activities here, especially in Sharm El Naga, which boasts exquisite colors of coral reefs and rare marine life. Safaga is famous for restaurants that offer seafood and fish. Luxor is about 231 km away."));
        arr.add(new Items("Soma Bay",R.drawable.somabay,"0122 326 0700",26.840104,33.950962,"Soma Bay is located 45 km south of Hurghada Airport and 25 km near Safaga. Soma Bay is characterized by beautiful coral reefs that attract diving enthusiasts. The Sheraton Soma Bay Resort and Kempinski Hotel are the most beautiful parts to visit in Soma Bay."));
        arr.add(new Items("Makadi Bay",R.drawable.makadibay,"null",26.982663,33.880581,"Makadi Bay is another bay of charming bays on the Red Sea coast of Egypt.It is located halfway between Hurghada and Safaga. Stunning and colorful, Makadi Bay also has stables with some of the best and most beautiful horses in Egypt. The gardens Msabhaa that offer a haven to relax and escape from the summer heat and the noise of life, of the most illustrious names here, \"Jazz Acquaviva Resort\" and \"Steijunbad Makadi Hôtel\" and many others."));
        arr.add(new Items("El Qoseir",R.drawable.elqoseir,"null",26.106493,34.279548,"It has been transformed from a gold mine in the Pharaonic era to a quiet and popular tourist resort for visitors, and is said to be called \"short\" because it shortens the distance between the coast and Upper Egypt, and is about two hours south of Hurghada and 3 hours from Luxor, and features a hot desert climate, so we recommend Visiting in the winter, which is warm in this city, Qusair is rich in its Pharaonic, Roman, Coptic and Islamic monuments, most notably the \"Castle of Quseir\", is also a vital point for diving because of its neighborhoods and coral rich, and the most important hotels and resorts in the beautiful Quseir And 'Radis N Blue Resort. \""));
        arr.add(new Items("Marsa Alam",R.drawable.marsaalam,"null",25.065149,34.897320,"Marsa Alam is about an hour and a half away from Quseir, one of the famous tourist places in Egypt, which is receiving increasing popularity from Arab and foreign visitors.Marsa Alam has a mild climate that makes it suitable for holidays all year round.Also, there is an airport about half an hour from the city center. Scuba diving is one of the most practiced marine sports here, where coral reefs and nature reserves are less frequent. The Dolphin Reserve provides a golden opportunity for those who dream of diving and playing with dolphins. Sharm El-Luli Beach is one of the most beautiful beaches in the world, which has recently gained its reputation. Advanced rating At the beaches of the world, the traveler will feel that in one of the charming beaches of the Maldives, where the soft white sand and shallow turquoise and scattered trees here and there like you are in a piece of paradise, and there are a number of recreational water parks such as \"Coraya\" water park, and the most famous parts Marsa Alam is worth a visit to the harbor or what is known as the \"Port Ghalib\", which has been established around many hotels and resorts in Marsa Alam, and has a beautiful pier along the beach and a number of cafes, restaurants and shops that sell gifts, souvenirs and Egyptian manufactures."));
        arr.add(new Items("Mersa Matruh",R.drawable.mersamatruh,"null",31.354742,27.236631,"Marsa Matrouh is about two and a half hours west of Alexandria. The mild climate Despite the high temperatures in summer, the city contains a number of ancient Pharaonic monuments such as \"Temple of Ramses II\" which is half an hour from\n" + " The city center is also famous for the beautiful sandy beaches that made it a prestigious place in the world of tourism and travel in addition to the hotels in Marsa Matrouh, which attracts a lot of visitors. In addition to the \"Cleopatra Beach\" which resembles a lake or a natural jacuzzi pool, the legend says that the beautiful Cleopatra was bathing in this place, while the beach \"Gram\" was named after the famous Egyptian artist \"Leila Murad\", which sang for love and love near him, and after that The traveler takes a premium Adequate love and imagination advise them to go to the \"Libyan market\" to tour a popular shopping and buy clothes, accessories, perfumes and spices that is unprecedented."));
        arr.add(new Items("El Alamein",R.drawable.elalamein,"null",30.824721,29.005837,"The city of El Alamein is located east of Marsa Matrouh, about an hour and a half from Alexandria, accessible by air where there is an international airport, in addition to a road linking it to Cairo and Alexandria,\n" + " It is a city with a mild heat and has a nice climate even in the hot summer, has been associated with the name of this city of World War II, where a fierce battle ended with the defeat of the Germans, and scattered military sites, memorials and cemeteries of the victims of the war or the so-called \"Commonwealth Cemetery\" Apart from the wars, El Alamein offers luxury and charming sandy beaches stretching on its Mediterranean coast. C. This small village has become a first-class resort, surrounded by hotels, luxury resorts, playgrounds, spaces and green gardens. Bar and Marassi Resort."));
        arr.add(new Items("Ain Sokhna",R.drawable.ainsokhna,"null",29.668633,32.337377,"Overlooking the Gulf of Suez and about an hour and a half from Cairo, Ain Sokhna is a popular place for Egyptians. This makes Ain Sokhna hotels and resorts suitable for holidays in summer and winter, has become a luxury tourist attraction, Ain Sokhna scattered along the huge resorts resembling small towns, in addition to the quiet sandy beaches where various activities and water sports such as go Jazz Little Venice Resort is one of the best entertainment centers, which offers fun and entertainment for adults and children, and there are dozens of restaurants, cafes, shops, galleries, cinema, entertainment cities, games and amusement parks for children, and so Ain Sokhna is a suitable city for family tourism. If you are near do not miss the opportunity to taste delicious seafood and fresh fish in the restaurant \"Abu Ali\" famous."));
        arr.add(new Items("Taba",R.drawable.taba,"null",29.492275,34.895381,"Taba is located on the Gulf of Aqaba, and is about three hours away from Sharm El Sheikh, where Taba hotels are considered to be quiet places that are not congested and is an ideal holiday for privacy seekers, summer temperatures rise above forty degrees, while mild winter, and what distinguishes these The spot is the meeting point of three countries, where you can see the coasts of Jordan, Saudi Arabia and Palestine from its dreamy beach, \"Castle Zaman\" offers a unique tourist experience in this simple resort that offers delicious cuisine cooked with stunning views of the Gulf of Aqaba, can take a boat trip to Pharaoh's Island which is listening Above it is the Saladin Castle as one of the most prominent Islamic monuments in the Taba region. Golfers can practice their favorite sport at the vast golf club \"Taba Heights\". Safari and adventure enthusiasts are on a date with a round of challenge aboard the quad bikes that start in A trip to the \"colored valley\" or the groove, a rare natural phenomenon in the Taba Reserve, extending in the form of twisted rock valleys with dazzling shapes and colors, exciting and exciting at a cost of $ 50 per person."));
        arr.add(new Items("Dahab",R.drawable.dahab,"null",28.509133,34.513607,"Overlooking the Gulf of Aqaba, Dahab is an hour and a half away from Sharm El Sheikh. It has gained a wide reputation in the world of tourism because of its nature reserves, scenic spots and beaches. For tourists, the name Dahab is associated with \"Blue Hole\" which attracts tourists from all over the world to participate in professional diving races. And Horse riding is also a popular sport in Dahab, where there are beautiful horses for a wonderful trip on the beach, bazaars and popular markets offering various Egyptian manufactures and gifts at competitive prices with a series of quiet cafes overlooking the sea, in addition to Elegant hotels and resorts such as Dahab Paradise and Sheikh Ali Dahab resorts. Dahab has many tourist offices that organize safaris to the oases, desert and mountains surrounding the area. Li Musa Mountain, where tranquility, comfort and stunning views, is located near this monastery many mountains suitable for climbing and oases inhabited by Bedouins who welcome every visitor with Arabic coffee, smile and friendly hospitality."));
        arr.add(new Items("Nuweiba",R.drawable.nuweiba,"null",28.973268,34.653517,"Located halfway between Dahab and Taba, Nuweiba is about an hour away from Dahab.It is a quiet natural place that has not been contaminated by human hands and modern civilization.Most of its inhabitants are Bedouin, and it is a haven for those looking for privacy in Nuweiba hotels that are calm and comfortable. On land and sea trips, in addition to the beautiful and uncrowded sandy beaches, where the ancient city of \"Nouamis\", which dates back to prehistoric times, and is spread by beautiful green oases such as the oasis \"Ain Khadra\" near the Monastery of \"Saint Catherine\", which contains a natural spring Of pure fresh water, it is the most important Yam camping in Nuweiba is a camping trip in the desert."));
        arr.add(new Items("Luxor",R.drawable.luxor,"null",25.687241,32.639631,"Luxor city is located in the center of Egypt on the Nile Delta, and about 3 and a half hours from Aswan,\n" +
                " Perhaps the trip to Egypt can only be completed by visiting this ancient city and ancient history, it has many treasures of the Pharaonic traveler dive into secrets and fictional stories, and Luxor hotels are witnessing a large crowd of visitors who flock to it from all poles of the earth, and one of the most important things to see The \"Karnak Temple\" and \"Luxor Temple\", which tell the history of Egypt through the ages and represent an architectural monument and art painting very well and dazzling, in addition to the \"Valley of the Kings\", which includes many of the Pharaonic tombs of the dynasties that ruled Egypt, the atmosphere may become very hot In summer in these areas After touring the worlds of the ancient Pharaohs, we recommend that you take a tour of the balloon and enjoy the view of the city and the vast desert on its outskirts. Busy from early morning to 12pm, if your visit is long, try a trip\n" +
                "In the boats that cruise the Nile down to the city of Aswan south of Luxor, with the melodies of music and folkloric performances of Egypt and the sound of the flute that dances the Nile under a clear sky and carefree."));
        arr.add(new Items("Aswan",R.drawable.askwan,"null",24.088932,32.899832,"Aswan is located to the south of Luxor, an ancient city and a popular tourist destination for many, Aswan is characterized by Nubian culture and civilization, which is still present today in the villages and surrounding landmarks,\n" +
                "Elephantine Island is one of the lively museums that strongly exhibit Nubian houses and culture. Aswan's hotels and resorts vary from luxurious to affordable, in addition to the fact that Aswan houses many temples and ancient monuments.One of the most important activities that can be done in Aswan is by boat on the Nile to visit the Nubian villages scattered around the Delta, where colorful and decorated houses and small domes Like fictional villages, there are a number of popular markets selling spices, tea and aromatic herbs. High-end in Egypt,\n" +
                " The garden extends throughout the island and includes different forms and types of flowers, trees and plantations, and there is a wonderful restaurant overlooking the Nile River, and deserves 'Elephant Island' also worth strolling in its ancient temples and picturesque scenery, representing Aswan a creative world with its islands and protected areas and the richness of cultures and dazzling history."));
        arr.add(new Items("Siwa Oasis",R.drawable.siwaqasis,"null",29.203180,25.519557,"Siwa Oasis is located in the desert of Western Egypt and is approximately 3 and a half hours from Marsa Matrouh,\n" +
                "Visiting this area requires great courage and determination from the tourist who dreams of a trip to a secluded world\n" +
                " A long and difficult road to reach Siwa gives it an added value and make it a precious jewel in the heart of the vast desert, where we recommend to visit as part of a day trip from the city of Mersa Matruh, but if you want to spend a night or more we recommend you to try a hotel Albabenshal, which you can reserve by entering his name into our search engine to access his page. One of the most important landmarks in Siwa is the Citadel of Shali, one of the oldest historic cities in Egypt, and the nearby Mount of the Dead, which evokes awe and desire to explore its sights and learn about its fairy tale, is a collection of tombs dating back To the Pharaonic era, characterized by its strange conical shape, and if the sea away from the oasis of Siwa, the \"Great Sand Sea\" is very close, what do you think of skiing on a sea of \u200B\u200Bsoft sand dunes extending to the borderless?!, And complete the excitement of quad biking and challenge the harsh desert, and during Touring you in\n" +
                "Sea of \u200B\u200Bsand You will meet the \"one well\", a well of hot sulfurous water as if the eye of the angry desert in this wonderful place, and do not forget to visit the \"Cleopatra bath\" to enjoy swimming in the spring of hot water, which is wrapped around orchards and green gardens as if a planet from another world What we are used to, Siwa Oasis and the nearby oases belong to an unconventional tourist experience for the tourist seeking the truth."));
        arr.add(new Items("pyramids",R.drawable.pyramids,"null",29.977293,31.132500,"Egyptian pyramids are ancient pyramid-shaped buildings located in Egypt. As of November 2008, sources indicate that 118 or 138 is the number of specific Egyptian pyramids. [1] [2] Most were built as tombs of the country's pharaohs and their companions during the ancient and central periods. [3] [4] [5] The earliest known Egyptian pyramids are located in Saqqara, northwest of Memphis. The oldest of these pyramids is the Pyramid of Djoser, which was built c. 2630-2610 BC during the Third Dynasty. [6] This pyramid and its surrounding complex were designed by the architect Imhotep, and is generally considered the oldest massive structure in the world constructed from apostate construction. [7] The most famous Egyptian pyramids are those in Giza, on the outskirts of Cairo. Many of the pyramids of Giza are among the largest structures ever built. [8] The Pyramid of Cheops in Giza is the largest Egyptian pyramid. It is the only one of the seven wonders of the ancient world that persists"));

        return arr;
    }
}

